var searchData=
[
  ['iangularunit',['IAngularUnit',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_angular_unit.html',1,'GeoAPI::CoordinateSystems']]],
  ['iattributestable',['IAttributesTable',['../interface_net_topology_suite_1_1_features_1_1_i_attributes_table.html',1,'NetTopologySuite::Features']]],
  ['ibinarygeometryreader',['IBinaryGeometryReader',['../interface_geo_a_p_i_1_1_i_o_1_1_i_binary_geometry_reader.html',1,'GeoAPI::IO']]],
  ['ibinarygeometrywriter',['IBinaryGeometryWriter',['../interface_geo_a_p_i_1_1_i_o_1_1_i_binary_geometry_writer.html',1,'GeoAPI::IO']]],
  ['iboundable',['IBoundable',['../interface_net_topology_suite_1_1_index_1_1_strtree_1_1_i_boundable.html',1,'NetTopologySuite::Index::Strtree']]],
  ['iboundable_3c_20envelope_2c_20titem_20_3e',['IBoundable&lt; Envelope, TItem &gt;',['../interface_net_topology_suite_1_1_index_1_1_strtree_1_1_i_boundable.html',1,'NetTopologySuite::Index::Strtree']]],
  ['iboundable_3c_20out_20t_2c_20out_20titem_20_3e',['IBoundable&lt; out T, out TItem &gt;',['../interface_geo_a_p_i_1_1_geometries_1_1_i_boundable_3_01out_01_t_00_01out_01_t_item_01_4.html',1,'GeoAPI::Geometries']]],
  ['iboundable_3c_20t_2c_20titem_20_3e',['IBoundable&lt; T, TItem &gt;',['../interface_net_topology_suite_1_1_index_1_1_strtree_1_1_i_boundable.html',1,'NetTopologySuite::Index::Strtree']]],
  ['iboundarynoderule',['IBoundaryNodeRule',['../interface_net_topology_suite_1_1_algorithm_1_1_i_boundary_node_rule.html',1,'NetTopologySuite::Algorithm']]],
  ['ibufferparameters',['IBufferParameters',['../interface_geo_a_p_i_1_1_operation_1_1_buffer_1_1_i_buffer_parameters.html',1,'GeoAPI::Operation::Buffer']]],
  ['icompoundcoordinatesystem',['ICompoundCoordinateSystem',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_compound_coordinate_system.html',1,'GeoAPI::CoordinateSystems']]],
  ['iconstraintsplitpointfinder',['IConstraintSplitPointFinder',['../interface_net_topology_suite_1_1_triangulate_1_1_i_constraint_split_point_finder.html',1,'NetTopologySuite::Triangulate']]],
  ['icoordinate',['ICoordinate',['../interface_geo_a_p_i_1_1_geometries_1_1_i_coordinate.html',1,'GeoAPI::Geometries']]],
  ['icoordinatebuffer',['ICoordinateBuffer',['../interface_geo_a_p_i_1_1_geometries_1_1_i_coordinate_buffer.html',1,'GeoAPI::Geometries']]],
  ['icoordinatefilter',['ICoordinateFilter',['../interface_geo_a_p_i_1_1_geometries_1_1_i_coordinate_filter.html',1,'GeoAPI::Geometries']]],
  ['icoordinatesequence',['ICoordinateSequence',['../interface_geo_a_p_i_1_1_geometries_1_1_i_coordinate_sequence.html',1,'GeoAPI::Geometries']]],
  ['icoordinatesequencefactory',['ICoordinateSequenceFactory',['../interface_geo_a_p_i_1_1_geometries_1_1_i_coordinate_sequence_factory.html',1,'GeoAPI::Geometries']]],
  ['icoordinatesequencefilter',['ICoordinateSequenceFilter',['../interface_geo_a_p_i_1_1_geometries_1_1_i_coordinate_sequence_filter.html',1,'GeoAPI::Geometries']]],
  ['icoordinatesystem',['ICoordinateSystem',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_coordinate_system.html',1,'GeoAPI::CoordinateSystems']]],
  ['icoordinatesystemauthorityfactory',['ICoordinateSystemAuthorityFactory',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_coordinate_system_authority_factory.html',1,'GeoAPI::CoordinateSystems']]],
  ['icoordinatesystemfactory',['ICoordinateSystemFactory',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_coordinate_system_factory.html',1,'GeoAPI::CoordinateSystems']]],
  ['icoordinatesystemservices_3c_20tcoordinatesystem_20_3e',['ICoordinateSystemServices&lt; TCoordinateSystem &gt;',['../interface_geo_a_p_i_1_1_i_coordinate_system_services_3_01_t_coordinate_system_01_4.html',1,'GeoAPI']]],
  ['icoordinatetransformation',['ICoordinateTransformation',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_transformations_1_1_i_coordinate_transformation.html',1,'GeoAPI::CoordinateSystems::Transformations']]],
  ['icoordinatetransformationfactory',['ICoordinateTransformationFactory',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_transformations_1_1_i_coordinate_transformation_factory.html',1,'GeoAPI::CoordinateSystems::Transformations']]],
  ['icrsobject',['ICRSObject',['../interface_net_topology_suite_1_1_coordinate_systems_1_1_i_c_r_s_object.html',1,'NetTopologySuite::CoordinateSystems']]],
  ['icurve',['ICurve',['../interface_geo_a_p_i_1_1_geometries_1_1_i_curve.html',1,'GeoAPI::Geometries']]],
  ['idatum',['IDatum',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_datum.html',1,'GeoAPI::CoordinateSystems']]],
  ['iellipsoid',['IEllipsoid',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_ellipsoid.html',1,'GeoAPI::CoordinateSystems']]],
  ['ienvelope',['IEnvelope',['../interface_geo_a_p_i_1_1_geometries_1_1_i_envelope.html',1,'GeoAPI::Geometries']]],
  ['iexpandable_3c_20t_20_3e',['IExpandable&lt; T &gt;',['../interface_geo_a_p_i_1_1_geometries_1_1_i_expandable_3_01_t_01_4.html',1,'GeoAPI::Geometries']]],
  ['ifeature',['IFeature',['../interface_net_topology_suite_1_1_features_1_1_i_feature.html',1,'NetTopologySuite::Features']]],
  ['ifittedcoordinatesystem',['IFittedCoordinateSystem',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_fitted_coordinate_system.html',1,'GeoAPI::CoordinateSystems']]],
  ['igeocentriccoordinatesystem',['IGeocentricCoordinateSystem',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_geocentric_coordinate_system.html',1,'GeoAPI::CoordinateSystems']]],
  ['igeodeticspatialreference',['IGeodeticSpatialReference',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_geodetic_spatial_reference.html',1,'GeoAPI::CoordinateSystems']]],
  ['igeographiccoordinatesystem',['IGeographicCoordinateSystem',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_geographic_coordinate_system.html',1,'GeoAPI::CoordinateSystems']]],
  ['igeographictransform',['IGeographicTransform',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_geographic_transform.html',1,'GeoAPI::CoordinateSystems']]],
  ['igeometry',['IGeometry',['../interface_geo_a_p_i_1_1_geometries_1_1_i_geometry.html',1,'GeoAPI::Geometries']]],
  ['igeometrycollection',['IGeometryCollection',['../interface_geo_a_p_i_1_1_geometries_1_1_i_geometry_collection.html',1,'GeoAPI::Geometries']]],
  ['igeometrycomponentfilter',['IGeometryComponentFilter',['../interface_geo_a_p_i_1_1_geometries_1_1_i_geometry_component_filter.html',1,'GeoAPI::Geometries']]],
  ['igeometryeditoroperation',['IGeometryEditorOperation',['../interface_net_topology_suite_1_1_geometries_1_1_utilities_1_1_geometry_editor_1_1_i_geometry_editor_operation.html',1,'NetTopologySuite::Geometries::Utilities::GeometryEditor']]],
  ['igeometryfactory',['IGeometryFactory',['../interface_geo_a_p_i_1_1_geometries_1_1_i_geometry_factory.html',1,'GeoAPI::Geometries']]],
  ['igeometryfilter',['IGeometryFilter',['../interface_geo_a_p_i_1_1_geometries_1_1_i_geometry_filter.html',1,'GeoAPI::Geometries']]],
  ['igeometryiosettings',['IGeometryIOSettings',['../interface_geo_a_p_i_1_1_i_o_1_1_i_geometry_i_o_settings.html',1,'GeoAPI::IO']]],
  ['igeometryreader_3c_20tsource_20_3e',['IGeometryReader&lt; TSource &gt;',['../interface_geo_a_p_i_1_1_i_o_1_1_i_geometry_reader_3_01_t_source_01_4.html',1,'GeoAPI::IO']]],
  ['igeometryservices',['IGeometryServices',['../interface_geo_a_p_i_1_1_i_geometry_services.html',1,'GeoAPI']]],
  ['igeometrywriter_3c_20tsink_20_3e',['IGeometryWriter&lt; TSink &gt;',['../interface_geo_a_p_i_1_1_i_o_1_1_i_geometry_writer_3_01_t_sink_01_4.html',1,'GeoAPI::IO']]],
  ['ihorizontalcoordinatesystem',['IHorizontalCoordinateSystem',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_horizontal_coordinate_system.html',1,'GeoAPI::CoordinateSystems']]],
  ['ihorizontaldatum',['IHorizontalDatum',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_horizontal_datum.html',1,'GeoAPI::CoordinateSystems']]],
  ['iindexvisitor',['IIndexVisitor',['../interface_net_topology_suite_1_1_index_1_1_i_index_visitor.html',1,'NetTopologySuite::Index']]],
  ['iinfo',['IInfo',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_info.html',1,'GeoAPI::CoordinateSystems']]],
  ['iintersectable_3c_20in_20t_20_3e',['IIntersectable&lt; in T &gt;',['../interface_geo_a_p_i_1_1_geometries_1_1_i_intersectable_3_01in_01_t_01_4.html',1,'GeoAPI::Geometries']]],
  ['iintersectsop',['IIntersectsOp',['../interface_net_topology_suite_1_1_index_1_1_strtree_1_1_abstract_s_t_rtree_3_01_t_00_01_t_item_01_4_1_1_i_intersects_op.html',1,'NetTopologySuite::Index::Strtree::AbstractSTRtree&lt; T, TItem &gt;']]],
  ['iitemdistance_3c_20t_2c_20titem_20_3e',['IItemDistance&lt; T, TItem &gt;',['../interface_net_topology_suite_1_1_index_1_1_strtree_1_1_i_item_distance_3_01_t_00_01_t_item_01_4.html',1,'NetTopologySuite::Index::Strtree']]],
  ['iitemvisitor_3c_20t_20_3e',['IItemVisitor&lt; T &gt;',['../interface_net_topology_suite_1_1_index_1_1_i_item_visitor_3_01_t_01_4.html',1,'NetTopologySuite::Index']]],
  ['ilineal',['ILineal',['../interface_geo_a_p_i_1_1_geometries_1_1_i_lineal.html',1,'GeoAPI::Geometries']]],
  ['ilinearring',['ILinearRing',['../interface_geo_a_p_i_1_1_geometries_1_1_i_linear_ring.html',1,'GeoAPI::Geometries']]],
  ['ilinearunit',['ILinearUnit',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_linear_unit.html',1,'GeoAPI::CoordinateSystems']]],
  ['ilinestring',['ILineString',['../interface_geo_a_p_i_1_1_geometries_1_1_i_line_string.html',1,'GeoAPI::Geometries']]],
  ['ilocalcoordinatesystem',['ILocalCoordinateSystem',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_local_coordinate_system.html',1,'GeoAPI::CoordinateSystems']]],
  ['ilocaldatum',['ILocalDatum',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_local_datum.html',1,'GeoAPI::CoordinateSystems']]],
  ['imapop',['IMapOp',['../interface_net_topology_suite_1_1_geometries_1_1_utilities_1_1_geometry_mapper_1_1_i_map_op.html',1,'NetTopologySuite::Geometries::Utilities::GeometryMapper']]],
  ['imathtransform',['IMathTransform',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_transformations_1_1_i_math_transform.html',1,'GeoAPI::CoordinateSystems::Transformations']]],
  ['imathtransformfactory',['IMathTransformFactory',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_transformations_1_1_i_math_transform_factory.html',1,'GeoAPI::CoordinateSystems::Transformations']]],
  ['imulticurve',['IMultiCurve',['../interface_geo_a_p_i_1_1_geometries_1_1_i_multi_curve.html',1,'GeoAPI::Geometries']]],
  ['imultilinestring',['IMultiLineString',['../interface_geo_a_p_i_1_1_geometries_1_1_i_multi_line_string.html',1,'GeoAPI::Geometries']]],
  ['imultipoint',['IMultiPoint',['../interface_geo_a_p_i_1_1_geometries_1_1_i_multi_point.html',1,'GeoAPI::Geometries']]],
  ['imultipolygon',['IMultiPolygon',['../interface_geo_a_p_i_1_1_geometries_1_1_i_multi_polygon.html',1,'GeoAPI::Geometries']]],
  ['imultisurface',['IMultiSurface',['../interface_geo_a_p_i_1_1_geometries_1_1_i_multi_surface.html',1,'GeoAPI::Geometries']]],
  ['incrementaldelaunaytriangulator',['IncrementalDelaunayTriangulator',['../class_net_topology_suite_1_1_triangulate_1_1_incremental_delaunay_triangulator.html',1,'NetTopologySuite::Triangulate']]],
  ['indexedfacetdistance',['IndexedFacetDistance',['../class_net_topology_suite_1_1_operation_1_1_distance_1_1_indexed_facet_distance.html',1,'NetTopologySuite::Operation::Distance']]],
  ['indexednestedringtester',['IndexedNestedRingTester',['../class_net_topology_suite_1_1_operation_1_1_valid_1_1_indexed_nested_ring_tester.html',1,'NetTopologySuite::Operation::Valid']]],
  ['indexedpointinarealocator',['IndexedPointInAreaLocator',['../class_net_topology_suite_1_1_algorithm_1_1_locate_1_1_indexed_point_in_area_locator.html',1,'NetTopologySuite::Algorithm::Locate']]],
  ['indexedpointinarealocator',['IndexedPointInAreaLocator',['../class_net_topology_suite_1_1_algorithm_1_1_indexed_point_in_area_locator.html',1,'NetTopologySuite::Algorithm']]],
  ['inodablesegmentstring',['INodableSegmentString',['../interface_net_topology_suite_1_1_noding_1_1_i_nodable_segment_string.html',1,'NetTopologySuite::Noding']]],
  ['inoder',['INoder',['../interface_net_topology_suite_1_1_noding_1_1_i_noder.html',1,'NetTopologySuite::Noding']]],
  ['interiorintersectionfinder',['InteriorIntersectionFinder',['../class_net_topology_suite_1_1_noding_1_1_interior_intersection_finder.html',1,'NetTopologySuite::Noding']]],
  ['interiorintersectionfinderadder',['InteriorIntersectionFinderAdder',['../class_net_topology_suite_1_1_noding_1_1_interior_intersection_finder_adder.html',1,'NetTopologySuite::Noding']]],
  ['interiorpointarea',['InteriorPointArea',['../class_net_topology_suite_1_1_algorithm_1_1_interior_point_area.html',1,'NetTopologySuite::Algorithm']]],
  ['interiorpointline',['InteriorPointLine',['../class_net_topology_suite_1_1_algorithm_1_1_interior_point_line.html',1,'NetTopologySuite::Algorithm']]],
  ['interiorpointpoint',['InteriorPointPoint',['../class_net_topology_suite_1_1_algorithm_1_1_interior_point_point.html',1,'NetTopologySuite::Algorithm']]],
  ['intersectionadder',['IntersectionAdder',['../class_net_topology_suite_1_1_noding_1_1_intersection_adder.html',1,'NetTopologySuite::Noding']]],
  ['intersectionfinderadder',['IntersectionFinderAdder',['../class_net_topology_suite_1_1_noding_1_1_intersection_finder_adder.html',1,'NetTopologySuite::Noding']]],
  ['intersectionmatrix',['IntersectionMatrix',['../class_geo_a_p_i_1_1_geometries_1_1_intersection_matrix.html',1,'GeoAPI::Geometries']]],
  ['interval',['Interval',['../struct_geo_a_p_i_1_1_data_structures_1_1_interval.html',1,'GeoAPI::DataStructures']]],
  ['interval',['Interval',['../class_net_topology_suite_1_1_index_1_1_bintree_1_1_interval.html',1,'NetTopologySuite::Index::Bintree']]],
  ['interval',['Interval',['../class_net_topology_suite_1_1_index_1_1_strtree_1_1_interval.html',1,'NetTopologySuite::Index::Strtree']]],
  ['intervalrtreebranchnode_3c_20t_20_3e',['IntervalRTreeBranchNode&lt; T &gt;',['../class_net_topology_suite_1_1_index_1_1_interval_r_tree_1_1_interval_r_tree_branch_node_3_01_t_01_4.html',1,'NetTopologySuite::Index::IntervalRTree']]],
  ['intervalrtreeleafnode_3c_20t_20_3e',['IntervalRTreeLeafNode&lt; T &gt;',['../class_net_topology_suite_1_1_index_1_1_interval_r_tree_1_1_interval_r_tree_leaf_node_3_01_t_01_4.html',1,'NetTopologySuite::Index::IntervalRTree']]],
  ['intervalrtreenode_3c_20t_20_3e',['IntervalRTreeNode&lt; T &gt;',['../class_net_topology_suite_1_1_index_1_1_interval_r_tree_1_1_interval_r_tree_node_3_01_t_01_4.html',1,'NetTopologySuite::Index::IntervalRTree']]],
  ['intervalsize',['IntervalSize',['../class_net_topology_suite_1_1_index_1_1_quadtree_1_1_interval_size.html',1,'NetTopologySuite::Index::Quadtree']]],
  ['inttoken',['IntToken',['../class_r_tools___n_t_s_1_1_util_1_1_int_token.html',1,'RTools_NTS::Util']]],
  ['iparameterinfo',['IParameterInfo',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_parameter_info.html',1,'GeoAPI::CoordinateSystems']]],
  ['ipoint',['IPoint',['../interface_geo_a_p_i_1_1_geometries_1_1_i_point.html',1,'GeoAPI::Geometries']]],
  ['ipointinarealocator',['IPointInAreaLocator',['../interface_net_topology_suite_1_1_algorithm_1_1_i_point_in_area_locator.html',1,'NetTopologySuite::Algorithm']]],
  ['ipointinring',['IPointInRing',['../interface_net_topology_suite_1_1_algorithm_1_1_i_point_in_ring.html',1,'NetTopologySuite::Algorithm']]],
  ['ipointongeometrylocator',['IPointOnGeometryLocator',['../interface_net_topology_suite_1_1_algorithm_1_1_locate_1_1_i_point_on_geometry_locator.html',1,'NetTopologySuite::Algorithm::Locate']]],
  ['ipolygon',['IPolygon',['../interface_geo_a_p_i_1_1_geometries_1_1_i_polygon.html',1,'GeoAPI::Geometries']]],
  ['ipolygonal',['IPolygonal',['../interface_geo_a_p_i_1_1_geometries_1_1_i_polygonal.html',1,'GeoAPI::Geometries']]],
  ['iprecisionmodel',['IPrecisionModel',['../interface_geo_a_p_i_1_1_geometries_1_1_i_precision_model.html',1,'GeoAPI::Geometries']]],
  ['ipreparedgeometry',['IPreparedGeometry',['../interface_geo_a_p_i_1_1_geometries_1_1_prepared_1_1_i_prepared_geometry.html',1,'GeoAPI::Geometries::Prepared']]],
  ['iprimemeridian',['IPrimeMeridian',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_prime_meridian.html',1,'GeoAPI::CoordinateSystems']]],
  ['iprojectedcoordinatesystem',['IProjectedCoordinateSystem',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_projected_coordinate_system.html',1,'GeoAPI::CoordinateSystems']]],
  ['iprojection',['IProjection',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_projection.html',1,'GeoAPI::CoordinateSystems']]],
  ['ipuntal',['IPuntal',['../interface_geo_a_p_i_1_1_geometries_1_1_i_puntal.html',1,'GeoAPI::Geometries']]],
  ['iquadedgelocator',['IQuadEdgeLocator',['../interface_net_topology_suite_1_1_triangulate_1_1_quad_edge_1_1_i_quad_edge_locator.html',1,'NetTopologySuite::Triangulate::QuadEdge']]],
  ['isegmentintersector',['ISegmentIntersector',['../interface_net_topology_suite_1_1_noding_1_1_i_segment_intersector.html',1,'NetTopologySuite::Noding']]],
  ['isegmentsetmutualintersector',['ISegmentSetMutualIntersector',['../interface_net_topology_suite_1_1_noding_1_1_i_segment_set_mutual_intersector.html',1,'NetTopologySuite::Noding']]],
  ['isegmentstring',['ISegmentString',['../interface_net_topology_suite_1_1_noding_1_1_i_segment_string.html',1,'NetTopologySuite::Noding']]],
  ['isegmentstringmerger',['ISegmentStringMerger',['../interface_net_topology_suite_1_1_noding_1_1_segment_string_dissolver_1_1_i_segment_string_merger.html',1,'NetTopologySuite::Noding::SegmentStringDissolver']]],
  ['isimilaritymeasure',['ISimilarityMeasure',['../interface_net_topology_suite_1_1_algorithm_1_1_match_1_1_i_similarity_measure.html',1,'NetTopologySuite::Algorithm::Match']]],
  ['ispatialindex',['ISpatialIndex',['../interface_net_topology_suite_1_1_index_1_1_i_spatial_index.html',1,'NetTopologySuite::Index']]],
  ['ispatialindex_3c_20t_20_3e',['ISpatialIndex&lt; T &gt;',['../interface_net_topology_suite_1_1_index_1_1_i_spatial_index_3_01_t_01_4.html',1,'NetTopologySuite::Index']]],
  ['issimpleop',['IsSimpleOp',['../class_net_topology_suite_1_1_operation_1_1_is_simple_op.html',1,'NetTopologySuite::Operation']]],
  ['isurface',['ISurface',['../interface_geo_a_p_i_1_1_geometries_1_1_i_surface.html',1,'GeoAPI::Geometries']]],
  ['isvalidop',['IsValidOp',['../class_net_topology_suite_1_1_operation_1_1_valid_1_1_is_valid_op.html',1,'NetTopologySuite::Operation::Valid']]],
  ['isweeplineoverlapaction',['ISweepLineOverlapAction',['../interface_net_topology_suite_1_1_index_1_1_sweepline_1_1_i_sweep_line_overlap_action.html',1,'NetTopologySuite::Index::Sweepline']]],
  ['itemboundable_3c_20t_2c_20titem_20_3e',['ItemBoundable&lt; T, TItem &gt;',['../class_net_topology_suite_1_1_index_1_1_strtree_1_1_item_boundable_3_01_t_00_01_t_item_01_4.html',1,'NetTopologySuite::Index::Strtree']]],
  ['iteratednoder',['IteratedNoder',['../class_net_topology_suite_1_1_noding_1_1_iterated_noder.html',1,'NetTopologySuite::Noding']]],
  ['itextgeometryreader',['ITextGeometryReader',['../interface_geo_a_p_i_1_1_i_o_1_1_i_text_geometry_reader.html',1,'GeoAPI::IO']]],
  ['itextgeometrywriter',['ITextGeometryWriter',['../interface_geo_a_p_i_1_1_i_o_1_1_i_text_geometry_writer.html',1,'GeoAPI::IO']]],
  ['itraversalvisitor',['ITraversalVisitor',['../interface_net_topology_suite_1_1_triangulate_1_1_quad_edge_1_1_i_traversal_visitor.html',1,'NetTopologySuite::Triangulate::QuadEdge']]],
  ['itrianglevisitor',['ITriangleVisitor',['../interface_net_topology_suite_1_1_triangulate_1_1_quad_edge_1_1_i_triangle_visitor.html',1,'NetTopologySuite::Triangulate::QuadEdge']]],
  ['iunit',['IUnit',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_unit.html',1,'GeoAPI::CoordinateSystems']]],
  ['iverticalcoordinatesystem',['IVerticalCoordinateSystem',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_vertical_coordinate_system.html',1,'GeoAPI::CoordinateSystems']]],
  ['iverticaldatum',['IVerticalDatum',['../interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_vertical_datum.html',1,'GeoAPI::CoordinateSystems']]]
];
