var searchData=
[
  ['scalednoder',['ScaledNoder',['../class_net_topology_suite_1_1_noding_1_1_scaled_noder.html',1,'NetTopologySuite::Noding']]],
  ['segment',['Segment',['../class_net_topology_suite_1_1_triangulate_1_1_segment.html',1,'NetTopologySuite::Triangulate']]],
  ['segmentintersectiondetector',['SegmentIntersectionDetector',['../class_net_topology_suite_1_1_noding_1_1_segment_intersection_detector.html',1,'NetTopologySuite::Noding']]],
  ['segmentintersectiontester',['SegmentIntersectionTester',['../class_net_topology_suite_1_1_operation_1_1_predicate_1_1_segment_intersection_tester.html',1,'NetTopologySuite::Operation::Predicate']]],
  ['segmentintersector',['SegmentIntersector',['../class_net_topology_suite_1_1_geometries_graph_1_1_index_1_1_segment_intersector.html',1,'NetTopologySuite::GeometriesGraph::Index']]],
  ['segmentnode',['SegmentNode',['../class_net_topology_suite_1_1_noding_1_1_segment_node.html',1,'NetTopologySuite::Noding']]],
  ['segmentnodelist',['SegmentNodeList',['../class_net_topology_suite_1_1_noding_1_1_segment_node_list.html',1,'NetTopologySuite::Noding']]],
  ['segmentoverlapaction',['SegmentOverlapAction',['../class_net_topology_suite_1_1_noding_1_1_m_c_index_segment_set_mutual_intersector_1_1_segment_overlap_action.html',1,'NetTopologySuite::Noding::MCIndexSegmentSetMutualIntersector']]],
  ['segmentoverlapaction',['SegmentOverlapAction',['../class_net_topology_suite_1_1_noding_1_1_m_c_index_noder_1_1_segment_overlap_action.html',1,'NetTopologySuite::Noding::MCIndexNoder']]],
  ['segmentpointcomparator',['SegmentPointComparator',['../class_net_topology_suite_1_1_noding_1_1_segment_point_comparator.html',1,'NetTopologySuite::Noding']]],
  ['segmentstringdissolver',['SegmentStringDissolver',['../class_net_topology_suite_1_1_noding_1_1_segment_string_dissolver.html',1,'NetTopologySuite::Noding']]],
  ['segmentstringutil',['SegmentStringUtil',['../class_net_topology_suite_1_1_noding_1_1_segment_string_util.html',1,'NetTopologySuite::Noding']]],
  ['shortcircuitedgeometryvisitor',['ShortCircuitedGeometryVisitor',['../class_net_topology_suite_1_1_geometries_1_1_utilities_1_1_short_circuited_geometry_visitor.html',1,'NetTopologySuite::Geometries::Utilities']]],
  ['sierpinskicarpetbuilder',['SierpinskiCarpetBuilder',['../class_net_topology_suite_1_1_shape_1_1_fractal_1_1_sierpinski_carpet_builder.html',1,'NetTopologySuite::Shape::Fractal']]],
  ['simpleedgesetintersector',['SimpleEdgeSetIntersector',['../class_net_topology_suite_1_1_geometries_graph_1_1_index_1_1_simple_edge_set_intersector.html',1,'NetTopologySuite::GeometriesGraph::Index']]],
  ['simplegeometryprecisionreducer',['SimpleGeometryPrecisionReducer',['../class_net_topology_suite_1_1_precision_1_1_simple_geometry_precision_reducer.html',1,'NetTopologySuite::Precision']]],
  ['simplemcsweeplineintersector',['SimpleMCSweepLineIntersector',['../class_net_topology_suite_1_1_geometries_graph_1_1_index_1_1_simple_m_c_sweep_line_intersector.html',1,'NetTopologySuite::GeometriesGraph::Index']]],
  ['simpleminimumclearance',['SimpleMinimumClearance',['../class_net_topology_suite_1_1_precision_1_1_simple_minimum_clearance.html',1,'NetTopologySuite::Precision']]],
  ['simplenestedringtester',['SimpleNestedRingTester',['../class_net_topology_suite_1_1_operation_1_1_valid_1_1_simple_nested_ring_tester.html',1,'NetTopologySuite::Operation::Valid']]],
  ['simplenoder',['SimpleNoder',['../class_net_topology_suite_1_1_noding_1_1_simple_noder.html',1,'NetTopologySuite::Noding']]],
  ['simplepointinarealocator',['SimplePointInAreaLocator',['../class_net_topology_suite_1_1_algorithm_1_1_locate_1_1_simple_point_in_area_locator.html',1,'NetTopologySuite::Algorithm::Locate']]],
  ['simplepointinarealocator',['SimplePointInAreaLocator',['../class_net_topology_suite_1_1_algorithm_1_1_simple_point_in_area_locator.html',1,'NetTopologySuite::Algorithm']]],
  ['simplepointinring',['SimplePointInRing',['../class_net_topology_suite_1_1_algorithm_1_1_simple_point_in_ring.html',1,'NetTopologySuite::Algorithm']]],
  ['simplesegmentsetmutualintersector',['SimpleSegmentSetMutualIntersector',['../class_net_topology_suite_1_1_noding_1_1_simple_segment_set_mutual_intersector.html',1,'NetTopologySuite::Noding']]],
  ['simplesnaprounder',['SimpleSnapRounder',['../class_net_topology_suite_1_1_noding_1_1_snapround_1_1_simple_snap_rounder.html',1,'NetTopologySuite::Noding::Snapround']]],
  ['simplesweeplineintersector',['SimpleSweepLineIntersector',['../class_net_topology_suite_1_1_geometries_graph_1_1_index_1_1_simple_sweep_line_intersector.html',1,'NetTopologySuite::GeometriesGraph::Index']]],
  ['sinestarfactory',['SineStarFactory',['../class_net_topology_suite_1_1_geometries_1_1_utilities_1_1_sine_star_factory.html',1,'NetTopologySuite::Geometries::Utilities']]],
  ['singlepassnoder',['SinglePassNoder',['../class_net_topology_suite_1_1_noding_1_1_single_pass_noder.html',1,'NetTopologySuite::Noding']]],
  ['sirtree_3c_20titem_20_3e',['SIRtree&lt; TItem &gt;',['../class_net_topology_suite_1_1_index_1_1_strtree_1_1_s_i_rtree_3_01_t_item_01_4.html',1,'NetTopologySuite::Index::Strtree']]],
  ['sirtreepointinring',['SIRtreePointInRing',['../class_net_topology_suite_1_1_algorithm_1_1_s_i_rtree_point_in_ring.html',1,'NetTopologySuite::Algorithm']]],
  ['snapifneededoverlayop',['SnapIfNeededOverlayOp',['../class_net_topology_suite_1_1_operation_1_1_overlay_1_1_snap_1_1_snap_if_needed_overlay_op.html',1,'NetTopologySuite::Operation::Overlay::Snap']]],
  ['snapoverlayop',['SnapOverlayOp',['../class_net_topology_suite_1_1_operation_1_1_overlay_1_1_snap_1_1_snap_overlay_op.html',1,'NetTopologySuite::Operation::Overlay::Snap']]],
  ['sortedpackedintervalrtree_3c_20t_20_3e',['SortedPackedIntervalRTree&lt; T &gt;',['../class_net_topology_suite_1_1_index_1_1_interval_r_tree_1_1_sorted_packed_interval_r_tree_3_01_t_01_4.html',1,'NetTopologySuite::Index::IntervalRTree']]],
  ['splitsegment',['SplitSegment',['../class_net_topology_suite_1_1_triangulate_1_1_split_segment.html',1,'NetTopologySuite::Triangulate']]],
  ['strtree_3c_20titem_20_3e',['STRtree&lt; TItem &gt;',['../class_net_topology_suite_1_1_index_1_1_strtree_1_1_s_t_rtree_3_01_t_item_01_4.html',1,'NetTopologySuite::Index::Strtree']]],
  ['subgraph',['Subgraph',['../class_net_topology_suite_1_1_planargraph_1_1_subgraph.html',1,'NetTopologySuite::Planargraph']]],
  ['sweeplineevent',['SweepLineEvent',['../class_net_topology_suite_1_1_geometries_graph_1_1_index_1_1_sweep_line_event.html',1,'NetTopologySuite::GeometriesGraph::Index']]],
  ['sweeplineevent',['SweepLineEvent',['../class_net_topology_suite_1_1_index_1_1_sweepline_1_1_sweep_line_event.html',1,'NetTopologySuite::Index::Sweepline']]],
  ['sweeplineindex',['SweepLineIndex',['../class_net_topology_suite_1_1_index_1_1_sweepline_1_1_sweep_line_index.html',1,'NetTopologySuite::Index::Sweepline']]],
  ['sweeplineinterval',['SweepLineInterval',['../class_net_topology_suite_1_1_index_1_1_sweepline_1_1_sweep_line_interval.html',1,'NetTopologySuite::Index::Sweepline']]],
  ['sweeplinenestedringtester',['SweeplineNestedRingTester',['../class_net_topology_suite_1_1_operation_1_1_valid_1_1_sweepline_nested_ring_tester.html',1,'NetTopologySuite::Operation::Valid']]],
  ['sweeplinesegment',['SweepLineSegment',['../class_net_topology_suite_1_1_geometries_graph_1_1_index_1_1_sweep_line_segment.html',1,'NetTopologySuite::GeometriesGraph::Index']]]
];
