var namespace_geo_a_p_i_1_1_coordinate_systems =
[
    [ "Transformations", "namespace_geo_a_p_i_1_1_coordinate_systems_1_1_transformations.html", "namespace_geo_a_p_i_1_1_coordinate_systems_1_1_transformations" ],
    [ "AxisInfo", "class_geo_a_p_i_1_1_coordinate_systems_1_1_axis_info.html", "class_geo_a_p_i_1_1_coordinate_systems_1_1_axis_info" ],
    [ "IAngularUnit", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_angular_unit.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_angular_unit" ],
    [ "ICompoundCoordinateSystem", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_compound_coordinate_system.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_compound_coordinate_system" ],
    [ "ICoordinateSystem", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_coordinate_system.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_coordinate_system" ],
    [ "ICoordinateSystemAuthorityFactory", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_coordinate_system_authority_factory.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_coordinate_system_authority_factory" ],
    [ "ICoordinateSystemFactory", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_coordinate_system_factory.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_coordinate_system_factory" ],
    [ "IDatum", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_datum.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_datum" ],
    [ "IEllipsoid", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_ellipsoid.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_ellipsoid" ],
    [ "IFittedCoordinateSystem", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_fitted_coordinate_system.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_fitted_coordinate_system" ],
    [ "IGeocentricCoordinateSystem", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_geocentric_coordinate_system.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_geocentric_coordinate_system" ],
    [ "IGeodeticSpatialReference", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_geodetic_spatial_reference.html", null ],
    [ "IGeographicCoordinateSystem", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_geographic_coordinate_system.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_geographic_coordinate_system" ],
    [ "IGeographicTransform", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_geographic_transform.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_geographic_transform" ],
    [ "IHorizontalCoordinateSystem", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_horizontal_coordinate_system.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_horizontal_coordinate_system" ],
    [ "IHorizontalDatum", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_horizontal_datum.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_horizontal_datum" ],
    [ "IInfo", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_info.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_info" ],
    [ "ILinearUnit", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_linear_unit.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_linear_unit" ],
    [ "ILocalCoordinateSystem", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_local_coordinate_system.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_local_coordinate_system" ],
    [ "ILocalDatum", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_local_datum.html", null ],
    [ "IParameterInfo", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_parameter_info.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_parameter_info" ],
    [ "IPrimeMeridian", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_prime_meridian.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_prime_meridian" ],
    [ "IProjectedCoordinateSystem", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_projected_coordinate_system.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_projected_coordinate_system" ],
    [ "IProjection", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_projection.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_projection" ],
    [ "IUnit", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_unit.html", null ],
    [ "IVerticalCoordinateSystem", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_vertical_coordinate_system.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_vertical_coordinate_system" ],
    [ "IVerticalDatum", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_i_vertical_datum.html", null ],
    [ "Parameter", "class_geo_a_p_i_1_1_coordinate_systems_1_1_parameter.html", "class_geo_a_p_i_1_1_coordinate_systems_1_1_parameter" ],
    [ "ProjectionParameter", "class_geo_a_p_i_1_1_coordinate_systems_1_1_projection_parameter.html", "class_geo_a_p_i_1_1_coordinate_systems_1_1_projection_parameter" ],
    [ "Wgs84ConversionInfo", "class_geo_a_p_i_1_1_coordinate_systems_1_1_wgs84_conversion_info.html", "class_geo_a_p_i_1_1_coordinate_systems_1_1_wgs84_conversion_info" ]
];