var namespace_geo_a_p_i_1_1_geometries =
[
    [ "Prepared", "namespace_geo_a_p_i_1_1_geometries_1_1_prepared.html", "namespace_geo_a_p_i_1_1_geometries_1_1_prepared" ],
    [ "Coordinate", "class_geo_a_p_i_1_1_geometries_1_1_coordinate.html", "class_geo_a_p_i_1_1_geometries_1_1_coordinate" ],
    [ "DimensionUtility", "class_geo_a_p_i_1_1_geometries_1_1_dimension_utility.html", "class_geo_a_p_i_1_1_geometries_1_1_dimension_utility" ],
    [ "Envelope", "class_geo_a_p_i_1_1_geometries_1_1_envelope.html", "class_geo_a_p_i_1_1_geometries_1_1_envelope" ],
    [ "IBoundable< out T, out TItem >", "interface_geo_a_p_i_1_1_geometries_1_1_i_boundable_3_01out_01_t_00_01out_01_t_item_01_4.html", "interface_geo_a_p_i_1_1_geometries_1_1_i_boundable_3_01out_01_t_00_01out_01_t_item_01_4" ],
    [ "ICoordinate", "interface_geo_a_p_i_1_1_geometries_1_1_i_coordinate.html", "interface_geo_a_p_i_1_1_geometries_1_1_i_coordinate" ],
    [ "ICoordinateBuffer", "interface_geo_a_p_i_1_1_geometries_1_1_i_coordinate_buffer.html", "interface_geo_a_p_i_1_1_geometries_1_1_i_coordinate_buffer" ],
    [ "ICoordinateFilter", "interface_geo_a_p_i_1_1_geometries_1_1_i_coordinate_filter.html", "interface_geo_a_p_i_1_1_geometries_1_1_i_coordinate_filter" ],
    [ "ICoordinateSequence", "interface_geo_a_p_i_1_1_geometries_1_1_i_coordinate_sequence.html", "interface_geo_a_p_i_1_1_geometries_1_1_i_coordinate_sequence" ],
    [ "ICoordinateSequenceFactory", "interface_geo_a_p_i_1_1_geometries_1_1_i_coordinate_sequence_factory.html", "interface_geo_a_p_i_1_1_geometries_1_1_i_coordinate_sequence_factory" ],
    [ "ICoordinateSequenceFilter", "interface_geo_a_p_i_1_1_geometries_1_1_i_coordinate_sequence_filter.html", "interface_geo_a_p_i_1_1_geometries_1_1_i_coordinate_sequence_filter" ],
    [ "ICurve", "interface_geo_a_p_i_1_1_geometries_1_1_i_curve.html", "interface_geo_a_p_i_1_1_geometries_1_1_i_curve" ],
    [ "IEnvelope", "interface_geo_a_p_i_1_1_geometries_1_1_i_envelope.html", "interface_geo_a_p_i_1_1_geometries_1_1_i_envelope" ],
    [ "IExpandable< T >", "interface_geo_a_p_i_1_1_geometries_1_1_i_expandable_3_01_t_01_4.html", "interface_geo_a_p_i_1_1_geometries_1_1_i_expandable_3_01_t_01_4" ],
    [ "IGeometry", "interface_geo_a_p_i_1_1_geometries_1_1_i_geometry.html", "interface_geo_a_p_i_1_1_geometries_1_1_i_geometry" ],
    [ "IGeometryCollection", "interface_geo_a_p_i_1_1_geometries_1_1_i_geometry_collection.html", "interface_geo_a_p_i_1_1_geometries_1_1_i_geometry_collection" ],
    [ "IGeometryComponentFilter", "interface_geo_a_p_i_1_1_geometries_1_1_i_geometry_component_filter.html", "interface_geo_a_p_i_1_1_geometries_1_1_i_geometry_component_filter" ],
    [ "IGeometryFactory", "interface_geo_a_p_i_1_1_geometries_1_1_i_geometry_factory.html", "interface_geo_a_p_i_1_1_geometries_1_1_i_geometry_factory" ],
    [ "IGeometryFilter", "interface_geo_a_p_i_1_1_geometries_1_1_i_geometry_filter.html", "interface_geo_a_p_i_1_1_geometries_1_1_i_geometry_filter" ],
    [ "IIntersectable< in T >", "interface_geo_a_p_i_1_1_geometries_1_1_i_intersectable_3_01in_01_t_01_4.html", "interface_geo_a_p_i_1_1_geometries_1_1_i_intersectable_3_01in_01_t_01_4" ],
    [ "ILineal", "interface_geo_a_p_i_1_1_geometries_1_1_i_lineal.html", null ],
    [ "ILinearRing", "interface_geo_a_p_i_1_1_geometries_1_1_i_linear_ring.html", "interface_geo_a_p_i_1_1_geometries_1_1_i_linear_ring" ],
    [ "ILineString", "interface_geo_a_p_i_1_1_geometries_1_1_i_line_string.html", "interface_geo_a_p_i_1_1_geometries_1_1_i_line_string" ],
    [ "IMultiCurve", "interface_geo_a_p_i_1_1_geometries_1_1_i_multi_curve.html", "interface_geo_a_p_i_1_1_geometries_1_1_i_multi_curve" ],
    [ "IMultiLineString", "interface_geo_a_p_i_1_1_geometries_1_1_i_multi_line_string.html", "interface_geo_a_p_i_1_1_geometries_1_1_i_multi_line_string" ],
    [ "IMultiPoint", "interface_geo_a_p_i_1_1_geometries_1_1_i_multi_point.html", null ],
    [ "IMultiPolygon", "interface_geo_a_p_i_1_1_geometries_1_1_i_multi_polygon.html", null ],
    [ "IMultiSurface", "interface_geo_a_p_i_1_1_geometries_1_1_i_multi_surface.html", null ],
    [ "IntersectionMatrix", "class_geo_a_p_i_1_1_geometries_1_1_intersection_matrix.html", "class_geo_a_p_i_1_1_geometries_1_1_intersection_matrix" ],
    [ "IPoint", "interface_geo_a_p_i_1_1_geometries_1_1_i_point.html", "interface_geo_a_p_i_1_1_geometries_1_1_i_point" ],
    [ "IPolygon", "interface_geo_a_p_i_1_1_geometries_1_1_i_polygon.html", "interface_geo_a_p_i_1_1_geometries_1_1_i_polygon" ],
    [ "IPolygonal", "interface_geo_a_p_i_1_1_geometries_1_1_i_polygonal.html", null ],
    [ "IPrecisionModel", "interface_geo_a_p_i_1_1_geometries_1_1_i_precision_model.html", "interface_geo_a_p_i_1_1_geometries_1_1_i_precision_model" ],
    [ "IPuntal", "interface_geo_a_p_i_1_1_geometries_1_1_i_puntal.html", null ],
    [ "ISurface", "interface_geo_a_p_i_1_1_geometries_1_1_i_surface.html", null ],
    [ "LocationUtility", "class_geo_a_p_i_1_1_geometries_1_1_location_utility.html", null ]
];