var namespace_geo_a_p_i_1_1_coordinate_systems_1_1_transformations =
[
    [ "ICoordinateTransformation", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_transformations_1_1_i_coordinate_transformation.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_transformations_1_1_i_coordinate_transformation" ],
    [ "ICoordinateTransformationFactory", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_transformations_1_1_i_coordinate_transformation_factory.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_transformations_1_1_i_coordinate_transformation_factory" ],
    [ "IMathTransform", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_transformations_1_1_i_math_transform.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_transformations_1_1_i_math_transform" ],
    [ "IMathTransformFactory", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_transformations_1_1_i_math_transform_factory.html", "interface_geo_a_p_i_1_1_coordinate_systems_1_1_transformations_1_1_i_math_transform_factory" ]
];